ui: mocha-bdd

browsers:
  - name: chrome
    version: -1..latest
  - name: safari
    version: -1..latest
  - name: firefox
    version: -1..latest
  - name: ie
    version: [9, latest]
  - name: microsoftedge
    version: -1..latest
